### ISSUE TITLE
Crashing while running the working example

### ISSUE THREAD

**Issue by TimSlendebroek** [daschw/SankeyPlots.jl#26] opened 2022-09-23 22:33 UTC
Running the working example on julia 1.8.1 is giving me some pointer malloc errors:

```julia
using SankeyPlots

src = [1, 1, 1, 1, 2, 2, 2, 3, 4, 5]
dst = [6, 3, 7, 4, 3, 7, 4, 7, 8, 8]
weights = [0.1, 0.3, 0.5, 0.5, 0.2, 2.8, 1, 0.45, 4.5, 3.3]

sankey(src, dst, weights)
```
error:
```
julia> sankey(src, dst, weights)
julia(83130,0x1024e8580) malloc: *** error for object 0xe00000000000000: pointer being freed was not allocated
julia(83130,0x1024e8580) malloc: *** set a breakpoint in malloc_error_break to debug

signal (6): Abort trap: 6
in expression starting at REPL[6]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 47680881 (Pool: 47660098; Big: 20783); GC: 29
```

This also seems be the same issue for @davide-f 's fork:
https://github.com/davide-f/SankeyPlots.jl

I am wondering if anyone else is having the same issue with prior julia versions?
I would be happy to provide additional information needed for debugging / or help.

Thanks!

**Comment by daschw** [comment] 2022-09-24 06:27
Thanks for reporting! I cannot reproduce this error with:
```julia
julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 8
  LD_LIBRARY_PATH = :/opt/gurobi950/linux64/lib:/opt/gurobi950/linux64/lib
  LD_PRELOAD = /usr/lib/libstdc++.so.6

(@test-sankey) pkg> st
Status `~/.julia/environments/test-sankey/Project.toml`
  [8fd88ec8] SankeyPlots v0.2.2
```

**Comment by TimSlendebroek** [comment] 2022-09-26 17:14
Thank you for your quick response, we do have a different OS and CPU

```julia
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 6 virtual cores



(@v1.8) pkg> st SankeyPlots
Status `~/.julia/environments/v1.8/Project.toml`
  [8fd88ec8] SankeyPlots v0.2.2
```
I am surprised if that would be causing this bug, not sure what it can be.

**Comment by sjkelly** [comment] 2023-04-10 17:33
This appears to be caused by `Clp.jl` : https://github.com/jump-dev/Clp.jl/issues/131

**Comment by sjkelly** [comment] 2023-04-11 15:01
An update of LayeredLayouts.jl has been tagged, so this should be fixed. Can you confirm?

**Comment by TimSlendebroek** [comment] 2023-04-11 15:41
> ```julia
> using SankeyPlots
> 
> src = [1, 1, 1, 1, 2, 2, 2, 3, 4, 5]
> dst = [6, 3, 7, 4, 3, 7, 4, 7, 8, 8]
> weights = [0.1, 0.3, 0.5, 0.5, 0.2, 2.8, 1, 0.45, 4.5, 3.3]
> 
> sankey(src, dst, weights)
> ```

Yup the update fixed it, thanks!!

<img width="587" alt="image" src="https://user-images.githubusercontent.com/32385057/231216008-3a9c442b-4117-406c-a6a6-fa71cef9d015.png">

**Comment by TimSlendebroek** [comment] 2023-04-11 15:41
> An update of LayeredLayouts.jl has been tagged, so this should be fixed. Can you confirm?

Yup the update fixed it, thanks!!

<img width="575" alt="image" src="https://user-images.githubusercontent.com/32385057/231216282-90ed83ec-3d0c-48e3-a09b-54c38df2d8a0.png">

**Closed as completed** 2023-04-11 15:41 UTC
